# Generated by Django 2.2.1 on 2019-05-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('genero', models.CharField(max_length=20)),
                ('independente', models.CharField(choices=[['SIM', 'Sim'], ['NAO', 'Não']], max_length=3)),
            ],
        ),
    ]
